### ISSUE TITLE
Player cannot Heal

### ISSUE THREAD

**Issue by BennXYZ** [BennXYZ/mech-diablo-programming-department#17]
Fehler beim ausführen von "TryHeal"

Tritt in der If-Abfrage
        if (healthContainer.Health < healthContainer.MaxHealth)
statt.

**Comment by BennXYZ** [comment]
Der Null-Abfang vor der Secondary-Ability fragt ab, ob die Secondary-WEAPON Null ist und nicht die Ability
Dadurch wird der Code im Player.Start() vorzeitig abgebrochen und die DamageAbleObject nicht zugewiesen

**Comment by crone66** [comment]
wurde von dir gefixed :)
