### ISSUE TITLE
Wenn man das Level restartet wird die falsche Scene geladen

### ISSUE THREAD

**Issue by crone66** [BennXYZ/mech-diablo-programming-department#30]
Vom Pausemenü: 
Wird das Spiel restartet, landet man in einem Testraum für den Boss,

**Comment by Discepless** [comment]
Die Szenen werden ständig geändert. Falls ihr diese Änderung macht - müsst ihr auch die Übergänge in Pause umändern.

Die ganze Logik steckt in "Gameinspector" script drin.

Hier sind die Methoden, die man ändern muss
`    public void CreditsScreen()
    {
        GlobalReferences.CurrentGameState = GlobalReferences.GameState.Play;
        SceneManager.LoadScene("Credits");
        UnfreezeAllPlayers();
    }

    public void Restart()
    {
        GlobalReferences.CurrentGameState = GlobalReferences.GameState.Play;
        SceneManager.LoadScene("Prototyp");
        UnfreezeAllPlayers();
    }

    public void MainMenu()
    {
        GlobalReferences.CurrentGameState = GlobalReferences.GameState.Play;
        SceneManager.LoadScene("MainMenu");
        UnfreezeAllPlayers();
    }`

Beim LoadScene müsst ihr dann die gewünschte Szene einfach einfügen.
