### ISSUE TITLE
Camera Adjustments

### ISSUE THREAD

**Issue by BennXYZ** [BennXYZ/mech-diablo-programming-department#5]
- Kamera bewegt sich Stückartig (Werte sind im Code integers statt floats?)
- da wir kein direktes Topdown haben wäre noch ein X- und Z- Offest praktisch (damit man auch schräg von der Seite schauen kann)
- Wäre praktisch, wenn die Kamera erkennt, wie viele Spieler im Game sind Bzw man durch einen int einstellen kann, wie viele Spieler berücksichtigt werden müssen. Im Augenblick geht sie immer von 4 Spielern aus.
- für einfache Kamera-Platzierung evtl. noch Schiebe-Balken einfügen

**Comment by Discepless** [comment]
1) done
2) ...
3) done
4) ...

Ich will kurz mit dir reden, bevor ich den code pushe =)
