### ISSUE TITLE
Enemies TODO

### ISSUE THREAD

**Issue by BennXYZ** [BennXYZ/mech-diablo-programming-department#7]
**Fabian**
- brauchen Health und passen ihre Schwierigkeit der Spieleranzahl an(Idee für Ansatz: Menge an Leben ändert sich nicht, jedoch nimmt ein Gegner weniger Schaden, wenn mehr Spieler ingame sind. Menge an Spieler wird jedes mal, wenn ein neuer Spieler beitritt/ austritt übergeben)
- Spieler und Enemies können besondere Status-Effekte erhalten, die ihr Verhalten beeinflussen:
    - Stun: Der Update-Teil für Movement und Shooting wird kurzzeitig übersprungen
    - Slow: Movement wird kurzzeitig beeinflusst
    - Burn: Man erhällt jede Sekunde 1 Schaden
- Gegner sollten in der Lage sein verschiedene Angriffe auszuführen
    - Normaler Schuss (wie er jetzt implementiert ist)
    (- Shotgun: 5 Projektile, voreinander verstreut, die nach einer kurzen Strecke verschwinden.)
Fokus auf variable Attacken entsprechend den Gegnertypen im Wiki

**Comment by Rikunaru** [comment]
Updated comment according to new Wiki elements.

**Comment by Rikunaru** [comment]
Health - Done
Variable Attacken - Done
Damagescaling zur Spieleranzahl WiP

**Comment by BennXYZ** [comment]
Coole sache ^^
kannst du das dann auch schon mal hochladen pls?

**Comment by Rikunaru** [comment]
To Do: Unity Event for EnemyDeath
