### ISSUE TITLE
Interface TODO

### ISSUE THREAD

**Issue by BennXYZ** [BennXYZ/mech-diablo-programming-department#8]
**Maksym & Richard**
- Informationen zu den einzelnen Spieler befinden sich in den Ecken des Bildschirms
(Spieler 1 oben links, Spieler 2 oben rechts, Spieler 3 unten links, Spieler 4 oben rechts)
diese zeigen die Leben eines einzelnen Spielers als Balken an.
- oben in der Mitte ist eine etwas größere Healthbar, welche die gesamt-Leben der Spieler darstellen
- Über jedem Spieler befindet sich ein Icon, das einzeigt um welchen Spieler es sich handel (P1, P2 etc)
- Über jedem Enemy ist ein roter Balken, der die Leben des Enemies darstellen.

**Gregor**
- im Hauptmenü bei der Spielerauswahl, muss es eine Klassen und Waffen- Auswahl geben
- visualisierung (zB "Press Start to Play", "Press A to Join" verschwindet wenn ein Spieler beiterete)
- siehe TODOs im Playerselection-Script

**Comment by GregorFrankenberg** [comment]
added visuability when player joins / leaves

**Comment by BennXYZ** [comment]
Für die Icons, die sich über Player/ Enemy befindet können erstmal Platzhalter-Sprites platziert werden.
