### ISSUE TITLE
Player-TODO

### ISSUE THREAD

**Issue by BennXYZ** [BennXYZ/mech-diablo-programming-department#9]
**Marcel:**
- 1 gesamt-Leben für alle 4 Spieler. Jeder Spieler erhällt für sich selbst nochmals Leben. Gehen die Leben eines einzelnen Spieler auf 0 ist er für ein paar Sekunden Kampfunfähig und regeneriert sich. Hierbei werden Punkte aus dem gesamt-Leben auf die eigenen Leben übertragen: 
- tragen 2 Waffen (zwischen L und R unterscheidbar)
- RB/LB feuert Primär-Angriff einer Waffe ab, RT/LT Sekundär-Angriff
- Steuerung:
    - A führt einen Dash in die Richtung aus, in die ein Spieler sich bewegt.
    - X führt eine direkt-Heilung der Leben eines einzelnen Spielers dar, wobei Punkte aus den Gesamt-Leben genommen werden..
    - Y führt eine Klassen-Spezifische Fähigkeit aus.
- kann unterschiedliche Status-Effekt haben (verlangsamt, eingefroren/Stun, brennend)

- Jeder Spieler besitzt eine Klasse (zB Scout oder Tank. genaue Klassen wurden noch nicht festgelegt). Je nach Klasse hat die Y-Taste eine andere Funktion und es können andere Waffen ausgewählt werden.
verschiedene Waffen: verschiedene Feuerrate, verschiedene Projektile, Projektil-reichweite (kann man ja evtl machen umd Nahkampfangriffe auch als Projektile zu coden ;) )

**Comment by BennXYZ** [comment]
New & Crazy Shit:
- Klassen sollten verschieden-viele Leben und verschiede Lauf-Geschwindigkeit besitzen
- Test-Waffen:
    - Minigun: feuert viele schnelle Projektile, die einzeln wenig Schaden zufügen.
    - Granatenwerfer: feuert von der Physik beeinflusste Projektile, die erst nach 2 Sekunden explodieren, und allen Gegnern in der Umgebung schaden
- Spieler-Projektile schaden andere Spieler nicht und fliegen einfach durcheinander durch
- Waffe besitzt Munition. Wenn Munition leer für kurze Zeit nicht verwendbar und Munition füllt sich wieder auf. Auch beide Waffen durch B Manuel nachladbar
- Skill auf Y Einsetzbar. erzeugt ein Schild in Blickrichtung, das Schaden abfängt.
- Blickrichtung des Spielers unabhängig von Bewegungs-Richtung (Strafing)

**Comment by crone66** [comment]
Alle punkte erledigt mit Ausnahme von:
- Status Effekten (werden von irgendjamnd anderen gemacht?)  
- Nahkampf

**Comment by BennXYZ** [comment]
Design-Änderung bezüglich der Munition:
- lädt sich nach kurzer Zeit, in der Waffe nicht genutzt wird, automatisch auf.
- B Taste wird für einen 2ten Spezial-Angriff genutzt.
- Für Prototyp-Klasse (Tank): Stomp, der allen Gegner um Spieler herum Betäubt (Status-Effekte noch nicht implementiert)

**Comment by crone66** [comment]
Ammo, und Stomp (ohne status effekt) sind fertig

**Comment by crone66** [comment]
Status Effekte sind fertig https://github.com/BennXYZ/mech-diablo-programming-department/commit/7d3c356a3b46f43aa7abe99d7c9de09ddb54ea49

**Comment by crone66** [comment]
Die Granate ist ab sofort eine Standard Aktion für alle Klassen. Sie liegt auf R3 und funktioniert genauso, wie bisher der Primärangriff des Granatwerfers war - welcher zum jetzigen Zeitpunkt allerdings nicht mehr im Spiel ist und der womöglich auch nicht mehr kommen wird
Der Dash ist nun auch auf L3 verfügbar. Die Funktion ist weiterhin ebenfalls auf A belegt
